### ISSUE TITLE
Game crashing after interacting with the camera item

### ISSUE THREAD

**Issue by Dioneum** [BlouFlin/Photography#12]
Hello! I had the following issue while trying to use the mod on my server, wonder what it might be. It happens just when I right-click the camera item to point it at something. I'm using minecraft 1.21 with the 1.02 version of the Photography mod

![Captura de tela 2024-06-19 085457](https://github.com/BlouFlin/Photography/assets/105397062/5b8bdbe7-5900-41b8-8b44-16baaddd2bbe)

**Comment by BlouFlin** [comment]
Hello ! Thanks for reporting the bug, I'm currently working on a fix. It seems to be a problem with the mod's networking

**Comment by BlouFlin** [comment]
Found a fix! I'm testing it tomorrow and publishing it on Modrinth if I found no more bug 👍

**Comment by BlouFlin** [comment]
It took a while, but I'm publishing 1.0.3 in just a few minutes!
