### ISSUE TITLE
Other players are kicked from the server when someone takes a photo

### ISSUE THREAD

**Issue by legdna** [BlouFlin/Photography#14]
After someone takes a photo, all players on the server except the person who took the photo are kicked from the server in version 1.0.3 of the mod for 1.20.6.

![error](https://github.com/BlouFlin/Photography/assets/61543298/f97708ae-d82d-47ea-b10a-2c7e538fe108)

**Comment by BlouFlin** [comment]
Hello! I can't reproduce the problem, could you please send me the logs and the list of other mods used if any?

**Comment by BlouFlin** [comment]
I finally managed to reproduce the problem using version 1.0.2 on the client side, are you all using the same version as the server?

**Comment by legdna** [comment]
Hello, it is indeed possible that some people still had version 1.0.2 installed on their PC. I'll try the mod again, making sure everyone is on 1.0.3, and I'll tell you again.

Sorry in advance for my English

**Comment by BlouFlin** [comment]
All right, thanks! If the problem is indeed due to a version difference, I'll try to implement a version difference warning in the next update to avoid this kind of issue :)
And don't worry, English isn't my first language either 👍

**Comment by legdna** [comment]
Hello, I've redone the tests and I can confirm that the problem was caused by people joining the server with a version lower than the one installed on the server.

Sorry for the late reply.
