### ISSUE TITLE
Potions and Tipped Arrows are renamed

### ISSUE THREAD

**Issue by Tenuuu** [BlouFlin/Photography#16]
With the mod installed, tipped arrows are all renamed to "Arrow of Poison" and potions are all renamed to "Water Bottle." Uninstalling the mod fixes this issue

**Comment by BlouFlin** [comment]
Thanks for reporting the bug, I can reproduce it so I'll look for the source of the problem :)

**Comment by BlouFlin** [comment]
I'm releasing the fix in version 1.0.4 on Modrinth soon!
