### ISSUE TITLE
not a issue but appreciation

### ISSUE THREAD

**Issue by Legendmanj** [BlouFlin/Photography#17]
mate, this is one of the best mods i have ever seen tbh. I love this lmao like that fact that vanilla clients can also see the picture and that it takes picture just like real camera including pixels just like minecraft!

the creativity on the first mod you have done is absolutely awesome! no cap.
looking forward to all the other mods that you can do and will be supporting your projects (;

`about the mod: increased pixels would make the mod better as some images taken seems to be more choppy compatively.`

**Comment by BlouFlin** [comment]
Thanks a lot! That's very kind, I'm very happy that people like my mod :)

Concerning the resolution of the photos, I'm limited by the size of the vanilla maps (128x128) and I don't think there's any way to increase this size without breaking vanilla compatibility... so I guess it's forever part of the "charm" of the mod haha
