### ISSUE TITLE
In the camera menu, pressing the "F1" key will breifly show your hud.

### ISSUE THREAD

**Issue by Just-MTTC** [BlouFlin/Photography#5]
In the camera menu, pressing the "F1" key will breifly show your hud, as quoted in the title. 

https://github.com/BlouFlin/Photography/assets/173006251/bde6267f-b6ca-4975-8f84-8808550ba44e

**Comment by BlouFlin** [comment]
Thank you for your feedback! It will be fixed in the next update (1.0.1) 👍
