### ISSUE TITLE
Advancements don't show up untill the camera gui is closed.

### ISSUE THREAD

**Issue by Just-MTTC** [BlouFlin/Photography#7]
Advancements don't show up untill the camera gui is closed and netiher does the sound, that isn't a big problem as it's very unlikely that a scenario like that happens.

https://github.com/BlouFlin/Photography/assets/173006251/a0500fb4-46df-44ee-9ff1-5d3226da8fcd

**Comment by BlouFlin** [comment]
The camera GUI works in the same way as when you hide the in-game HUD with F1, and so waits for the HUD to reappear before announcing advancements. This prevents distractions while you're taking a photo, and also avoids other problems related to photo rendering 👍

**Comment by BlouFlin** [comment]
Duplicate of #8
